disabled_rules:
  #shorthand_operator
  
opt_in_rules:

included:

excluded:
  - Pods
  - Carthage
  - SourcePackages
  - Generated

line_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 1
  validates_start_with_lowercase: false
